spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9410
    sender:
      type: web
  application:
    name: service-student-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studentapi?useUnicode=true&CharacterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Kuala_Lumpur
    username: '{cipher}50b2145274b6e8fa8115f968ea31b4a3a3d715c69cbb149c260bfc0764e9a757'
    password: '{cipher}d90589026421c4c631c1c2ff25542d08e00222682e04102ff544727c61987608'

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9000

eureka:
  client:
    #    注册中心的连接地址
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    #    发送一次心跳证明自己依然存活
    lease-renewal-interval-in-seconds: 2
    #    如果超过时间就代表自己已死
    lease-expiration-duration-in-seconds: 10
    #    告诉服务端，服务实例以IP作为连接，而不是取机器名
    prefer-ip-address: true
    #    名字
    instance-id: springcloud-client-provider-2
