server:
  port: 81



eureka:
  client:
    #    注册中心的连接地址
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    #    发送一次心跳证明自己依然存活
    lease-renewal-interval-in-seconds: 2
    #    如果超过时间就代表自己已死
    lease-expiration-duration-in-seconds: 10
    #    告诉服务端，服务实例以IP作为连接，而不是取机器名
    prefer-ip-address: true
    #    名字
    instance-id: springcloud-service-zuul

spring:
  application:
    name: service-student-service-zuul

zuul:
  #禁用SendErrorFilter过滤器
  SendErrorFilter:
    error:
      disable: true
  routes:
    student-service:
      service-id: service-student-consumer-2
      # 通过这个URL访问（ http://localhost:81/springcloud/service/api/v1/student/feign/find/name/chl ）
      path: /service/**
  ignored-services: "*"
  # prefix: /springcloud
